name: "Create multi-arch docker image"
inputs:
  registry:
    required: true
    description: "Image registry FQDN"
  username:
    required: true
    description: "Login username for the registry"
  password:
    required: true
    description: "Login password for the registry"
  image:
    required: true
    description: "Image tag"
  image-version:
    required: true
    description: "Image version"
runs:
  using: "composite"
  steps:
  - name: Login to the registry
    uses: docker/login-action@v3
    with:
      registry: ${{ inputs.registry }}
      username: ${{ inputs.username }}
      password: ${{ inputs.password }}
  - name: Create multi-arch image manifest latest
    shell: bash
    run: |
      docker manifest create ${{ inputs.image }}:latest \
          --amend ${{ inputs.image }}:latest-amd64 \
          --amend ${{ inputs.image }}:latest-arm64
      docker manifest push ${{ inputs.image }}:latest
  - name: Create multi-arch image manifest version
    shell: bash
    run: |
      docker manifest create ${{ inputs.image }}:${{ inputs.image-version }} \
          --amend ${{ inputs.image }}:${{ inputs.image-version }}-amd64 \
          --amend ${{ inputs.image }}:${{ inputs.image-version }}-arm64
      docker manifest push ${{ inputs.image }}:${{ inputs.image-version }}
