name: Build image

on:
  schedule:
    - cron: '0 0 15 * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      image_version: ${{ steps.create_tag.outputs.IMAGE_VERSION }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: -1
      - name: create tag
        id: create_tag
        run: |
          YY=$(date +%y)
          MM=$(date +%m)
          REV=0
          while git show-ref --tags | grep -q "refs/tags/${YY}.${MM}.${REV}"; do
          REV=$((REV+1))
          done
          echo "IMAGE_VERSION=${YY}.${MM}.${REV}" >> $GITHUB_OUTPUT

  build-amd64:
    runs-on: ubuntu-24.04
    needs: [prepare]
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: checkout
        uses: actions/checkout@v5

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          provenance: false
          tags: |
            ghcr.io/being24/latex-docker-base:latest-amd64
            ghcr.io/being24/latex-docker-base:${{ needs.prepare.outputs.image_version }}-amd64

  build-arm64:
    runs-on: ubuntu-24.04-arm
    needs: [prepare]
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: checkout
        uses: actions/checkout@v5

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          provenance: false
          tags: |
            ghcr.io/being24/latex-docker-base:latest-arm64
            ghcr.io/being24/latex-docker-base:${{ needs.prepare.outputs.image_version }}-arm64

  manifest:
    runs-on: ubuntu-latest
    needs: [prepare, build-amd64, build-arm64]
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: -1

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifest images
        uses: Noelware/docker-manifest-action@v1
        with:
          inputs: ghcr.io/being24/latex-docker-base:latest-amd64,ghcr.io/being24/latex-docker-base:latest-arm64
          tags: ghcr.io/being24/latex-docker-base:latest,ghcr.io/being24/latex-docker-base:${{ needs.prepare.outputs.image_version }}
          push: true

      - name: Create GitHub Releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=${{ needs.prepare.outputs.image_version }}
          if git show-ref --tags | grep -q "refs/tags/${TAG}"
          then
            echo "${TAG} exists. Skipped"
            exit 0
          fi
          git tag ${TAG}
          git push --tags
          gh release create ${TAG} --generate-notes