name: Build image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
    steps:
      - uses: actions/checkout@v4
      - name: create tag
        run: |
          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - name: Login to docker.io
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/${{ matrix.arch }}
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/${{ matrix.arch }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/being24/latex-docker-base:latest-${{ matrix.arch }}
            ghcr.io/being24/latex-docker-base:${{ env.VERSION }}-${{ matrix.arch }}
            ${{ secrets.DOCKERHUB_USERNAME }}/latex-docker-base:latest-${{ matrix.arch }}
            ${{ secrets.DOCKERHUB_USERNAME }}/latex-docker-base:${{ env.VERSION }}-${{ matrix.arch }}
  manifest:
    runs-on: ubuntu-22.04
    needs: build
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: -1
      - name: create tag
        run: |
          echo "IMAGE_VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - uses: ./.github/actions/create-multi-arch-image
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ghcr.io/being24/latex-docker-base
          image-version: ${{ env.IMAGE_VERSION }}
      - uses: ./.github/actions/create-multi-arch-image
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: ${{ secrets.DOCKERHUB_USERNAME }}/latex-docker-base
          image-version: ${{ env.IMAGE_VERSION }}
      - name: Create GitHub Releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=v$(cat VERSION)
          if git show-ref --tags | grep -q "refs/tags/${TAG}"
          then
            echo "${TAG} exists. Skipped"
            exit 0
          fi
          git tag ${TAG}
          git push --tags
          gh release create ${TAG} --generate-notes

